### PR TITLE
added PKCS5 support to ZCL_AES_UTILITY

### PR DESCRIPTION
**Pull request by jeremycoppey**
added PKCS5 support to ZCL_AES_UTILITY
please merge, this has been tested and confirmed it works
Thanks

### CODE REVIEW

**Review by larshp — APPROVED** [review]
LGTM

**Comment by larshp** [comment]
If you have time, please add unit tests for the new padding

**Comment by Sumu-Ning** [comment]
Thank you for your help. In your ABAP tools, do you have some Mock Utilities which are similar to Mockito in the Java world?

**Comment by larshp** [comment]
@Sumu-Ning depends on your ABAP version, but https://github.com/sbcgua/mockup_loader might help

**Comment by Sumu-Ning** [comment]
Good to know, thank you!

**Pull request merged**
