### PR TITLE
remove data element dependencies

### PR DESCRIPTION
**Pull request by WegnerDan**
replaced char10 with relevant class types

replaced int4 with i

replaced boole_d with abap_bool

### CODE REVIEW

**Comment by Sumu-Ning** [comment]
Looks good to me, but probably you would like @larshp to review it, since I am not working on ABAP any more.  
Also, probably it is better to squash the 2 commits into a single one?

**Comment by WegnerDan** [comment]
> Looks good to me, but probably you would like @larshp to review it, since I am not working on ABAP any more.

Should I create a fork of his fork and a new pull request?

>  Also, probably it is better to squash the 2 commits into a single one?

I agree, I missed a couple of data elements in the first commit, but how do I do that? I don't use a whole lot of git.

**Comment by Sumu-Ning** [comment]
> > Looks good to me, but probably you would like @larshp to review it, since I am not working on ABAP any more.
> 
> Should I create a fork of his fork and a new pull request?

He should have full control of this repository.

> > Also, probably it is better to squash the 2 commits into a single one?
> 
> I agree, I missed a couple of data elements in the first commit, but how do I do that? I don't use a whole lot of git.

you can do the following, which will remove the last commit, but keep the change 
```bash
git reset HEAD~1 --soft
```
then, this will modify the latest commit (which was the second last, but we just cancelled the last one)
```bash
git commit --amend
```

**Comment by WegnerDan** [comment]
Thank you

**Comment by larshp** [comment]
I'll take a look, and squash before merging to master, I typically do this if there are multiple commits, no need to change the branch, this is built-in to github
image

**Review by larshp — APPROVED** [review]
Looks good to me, thanks

**Pull request merged**
